In [80]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [83]:
dataframe = pandas.read_csv("alb.csv")
#type(dataframe)
dataframe

,Year,Country,Region,Songlanguage,Artistgender,GroupSolo,Place,Points,HostCountry,Hostregion,Country.1,10Region,ApproximateBettingPrices,Albania
0,2008,3,4,3,2,2,20,45,3,1,0,0,95,0
1,2008,1,2,2,4,3,25,14,2,3,0,0,265,0
2,2008,2,3,3,3,3,17,43,3,1,0,0,270,0
3,2008,1,1,3,3,2,23,14,3,2,0,0,348,0
4,2008,3,3,1,3,3,4,198,2,1,0,0,14,2
5,2008,3,2,2,4,3,10,105,2,1,0,1,29,0
6,2008,1,1,3,4,3,9,124,2,3,0,0,120,4
7,2008,2,3,1,4,2,22,35,2,1,0,0,31,0
8,2008,1,2,4,2,2,21,42,3,2,0,1,248,0
9,2008,3,2,2,3,3,24,14,2,1,0,0,208,0
10,2008,3,3,2,2,2,14,64,1,1,0,0,105,0
11,2008,1,1,1,4,2,7,131,3,3,0,0,34,10
12,2008,4,3,1,3,3,13,69,2,4,0,0,59,0
13,2008,1,3,4,2,2,12,83,2,3,0,0,62,0
14,2008,4,3,1,3,3,18,47,2,4,0,0,16,3
15,2008,3,2,1,4,3,15,60,4,3,0,0,106,0
16,2008,3,4,3,3,3,11,83,4,1,0,0,84,0
17,2008,3,1,2,3,3,2,226,2,3,0,0,5,8
18,2008,3,1,3,4,3,19,47,1,4,0,0,91,0
19,2008,1,1,4,2,2,8,124,2,3,0,0,90,0
20,2008,1,3,1,3,3,3,215,4,4,0,0,9,12
21,2008,2,1,1,4,3,16,55,1,3,0,0,43,1
22,2008,1,3,2,3,3,6,150,4,2,1,1,11,5
23,2008,3,4,3,4,3,1,266,2,3,0,0,3,6
24,2008,4,2,1,3,3,5,182,2,4,0,0,48,7
25,2007,1,1,3,3,3,11,106,4,4,0,0,188,8
26,2007,4,2,2,4,2,20,43,2,3,0,0,125,12
27,2007,4,1,2,4,3,6,145,1,3,0,0,11,2
28,2007,3,2,3,2,2,24,5,4,2,0,0,100,5
29,2007,2,2,2,3,3,17,53,3,4,0,1,68,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,1999,4,3,1,1,1,5,93,1,4,1,1,0,0
237,1999,4,2,4,1,1,15,32,1,1,0,0,0,0
238,1999,3,1,4,1,1,3,140,4,3,0,0,0,0
239,1999,2,4,2,1,1,7,86,1,2,0,0,0,0
240,1999,2,4,3,1,1,6,90,3,1,0,0,0,0
241,1998,2,4,1,1,1,5,131,1,1,0,0,0,0
242,1998,4,3,3,1,1,20,12,1,2,0,0,0,0
243,1998,4,4,3,1,1,24,3,2,3,0,0,0,0
244,1998,4,4,3,1,1,16,21,2,1,0,0,0,0
245,1998,2,2,3,1,1,25,0,4,3,0,0,0,0
246,1998,1,3,1,1,1,21,8,4,1,0,0,0,0
247,1998,2,4,4,1,1,17,19,3,4,0,0,0,0
248,1998,2,4,2,1,1,1,172,2,3,0,0,0,0
249,1998,4,4,2,1,1,7,86,1,4,0,0,0,0
250,1998,4,1,4,1,1,3,165,3,2,0,0,0,0
251,1998,4,4,4,1,1,23,4,4,1,0,0,0,0
252,1998,3,1,3,1,1,18,17,2,3,0,0,0,0
253,1998,1,3,4,1,1,9,64,1,1,0,0,0,0
254,1998,3,3,4,1,1,12,36,3,4,0,0,0,0
255,1998,3,4,3,1,1,22,6,4,4,0,0,0,0
256,1998,2,4,4,1,1,2,166,2,3,1,1,0,0
257,1998,3,2,4,1,1,11,37,3,4,0,0,0,0
258,1998,4,4,4,1,1,4,150,1,1,0,0,0,0
259,1998,2,2,4,1,1,10,53,3,2,0,0,0,0
260,1998,1,1,2,1,1,6,122,4,4,0,0,0,0
261,1998,4,1,1,1,1,15,22,4,4,0,0,0,0
262,1998,1,4,2,1,1,8,79,1,3,0,0,0,0
263,1998,3,2,2,1,1,12,36,1,4,0,0,0,0
264,1998,2,3,3,1,1,14,25,2,1,0,0,0,0
265,1998,1,4,3,1,1,19,16,1,1,0,0,0,0

In [84]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

In [85]:
dataset = dataframe.values

In [93]:

# split into input (X) and output (Y) variables
X = dataset[:,0:13]
Y = dataset[:,13]
type(X)

numpy.ndarray

In [87]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [88]:
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=13, activation='relu'))
	model.add(Dense(11, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [89]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

In [90]:
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [92]:
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Accuracy: 23.35% (35.09%)

In [94]:
i=10

In [95]:
str(i)

'10'